runtime: python39
entrypoint: gunicorn -b :$PORT main:app
env_variables:
  FLASK_SECRET_KEY: "tu_clave_secreta_aqui"

handlers:
- url: /static
  static_dir: static/  # Ruta a la carpeta de archivos estáticos como CSS, JavaScript, imágenes, etc.

- url: /templates
  static_dir: templates/  # Ruta a la carpeta de archivos html.

- url: /img
  static_dir: web/img  # Ruta a la carpeta de imágenes
  secure: always

- url: /css
  static_dir: web/css  # Ruta a la carpeta de archivos CSS
  secure: always

- url: /js
  static_dir: web/js  # Ruta a la carpeta de archivos JavaScript
  secure: always

- url: /contactform
  static_dir: web/contactform  # Ruta a la carpeta de archivos JavaScript
  secure: always

- url: /(.*\.(ico|json))$
  static_files: \1
  upload: (.*\.(ico|json))$

- url: /node_modules
  static_dir: node_modules/  # Carpeta entera y su contenido serán servidos como archivos estáticos
  secure: always

- url: /.*
  script: auto  # Esto le indica a App Engine que use gunicorn para ejecutar la aplicación Flask

- url: /app
  script: app:app  # Aquí, app es tu aplicación en app.py
